### ISSUE TITLE
PR LEDs port forwarding

### ISSUE THREAD

**Issue by ligi** [ethdevberlin/server#2]
waiting for @chriseth providing me with the IP and port for the LEDs

**Comment by chriseth** [comment]
Not sure if the IP will be stable, but it is: espressif.ethdev (10.10.42.119)
Internal port should be 80. External port 80 would also be great.

**Comment by ligi** [comment]
```
# curl 10.10.42.119:80
#curl: (7) Failed to connect to 10.10.42.119 port 80: Connection refused
```

but if the service is up you should be able to reach it via: https://espressiv.komputing.org

**Comment by chriseth** [comment]
Works!

**Comment by ligi** [comment]
:tada:
